package moe.wolfgirl.probejs.lang.schema;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import dev.latvian.mods.kubejs.recipe.component.RecipeComponentType;
import net.minecraft.resources.ResourceLocation;

import java.util.*;

public class ComponentSchema {
    private final Set<ResourceLocation> simpleSchemas = new HashSet<>();
    private final Map<ResourceLocation, JsonObject> compoundSchemas = new HashMap<>();

    /**
     * Register the recipe component to schema as a plain ID.
     *
     * @param recipeComponent the component
     */
    public void registerSimple(RecipeComponentType<?> recipeComponent) {
        simpleSchemas.add(recipeComponent.id());
    }

    /**
     * Register the recipe component to schema as an object.
     * <br>
     * E.g. list
     *
     * @param recipeComponent the component
     * @param content         the schema following JSON schema 2020-07 specification (or whatever, I forgot)
     */
    public void registerCompound(RecipeComponentType<?> recipeComponent, JsonObject content) {
        compoundSchemas.put(recipeComponent.id(), content);
    }

    public Set<ResourceLocation> getSimpleSchemas() {
        return simpleSchemas;
    }

    public Map<ResourceLocation, JsonObject> getCompoundSchemas() {
        return compoundSchemas;
    }

    // Helpers generated by Google Gemini 2.5 Pro, haha

    // --- Schema Generation Helpers ---

    /**
     * Creates a JSON schema for a string.
     * Schema: {@code {"type": "string"}}
     *
     * @return a JsonObject representing the string schema.
     */
    public JsonObject string() {
        JsonObject schema = new JsonObject();
        schema.addProperty("type", "string");
        return schema;
    }

    /**
     * Creates a JSON schema for a number (can be integer or floating-point).
     * Schema: {@code {"type": "number"}}
     *
     * @return a JsonObject representing the number schema.
     */
    public JsonObject number() {
        JsonObject schema = new JsonObject();
        schema.addProperty("type", "number");
        return schema;
    }

    /**
     * Creates a JSON schema for an integer.
     * Schema: {@code {"type": "integer"}}
     *
     * @return a JsonObject representing the integer schema.
     */
    public JsonObject integer() {
        JsonObject schema = new JsonObject();
        schema.addProperty("type", "integer");
        return schema;
    }

    /**
     * Creates a JSON schema for a boolean.
     * Schema: {@code {"type": "boolean"}}
     *
     * @return a JsonObject representing the boolean schema.
     */
    public JsonObject bool() {
        JsonObject schema = new JsonObject();
        schema.addProperty("type", "boolean");
        return schema;
    }

    /**
     * Creates a JSON schema for a string that must be one of the specified values.
     * Schema: {@code {"type": "string", "enum": ["value1", "value2", ...]}}
     *
     * @param values The allowed string values.
     * @return a JsonObject representing the enum schema.
     */
    public JsonObject enumOf(String... values) {
        JsonObject schema = string(); // Start with a basic string schema
        JsonArray enumValues = new JsonArray();
        for (String value : values) {
            enumValues.add(new JsonPrimitive(value));
        }
        schema.add("enum", enumValues);
        return schema;
    }

    /**
     * Creates a JSON schema for a list (array) where each item must match the provided item schema.
     * Schema: {@code {"type": "array", "items": { ...item schema... }}}
     *
     * @param itemSchema The schema for each individual item in the list.
     * @return a JsonObject representing the list schema.
     */
    public JsonObject listOf(JsonObject itemSchema) {
        JsonObject schema = new JsonObject();
        schema.addProperty("type", "array");
        schema.add("items", itemSchema);
        return schema;
    }

    /**
     * Begins the construction of a JSON schema for an object.
     * Use the returned builder to define properties.
     *
     * @return a new {@link ObjectSchemaBuilder} instance.
     */
    public ObjectSchemaBuilder object() {
        return new ObjectSchemaBuilder();
    }

    /**
     * A fluent builder for creating complex object schemas.
     * It is an inner class so that it can be instantiated via {@link ComponentSchema#object()}.
     */
    public static class ObjectSchemaBuilder {
        private final Map<String, JsonObject> properties = new LinkedHashMap<>();
        private final Set<String> required = new LinkedHashSet<>();

        /**
         * Adds an optional property to the object schema.
         *
         * @param name   The name of the property.
         * @param schema The schema for the property's value.
         * @return this builder for chaining.
         */
        public ObjectSchemaBuilder withProperty(String name, JsonObject schema) {
            this.properties.put(name, schema);
            return this;
        }

        /**
         * Adds a required property to the object schema.
         * This is a convenience method that calls {@link #withProperty(String, JsonObject)}
         * and also marks the property as required.
         *
         * @param name   The name of the property.
         * @param schema The schema for the property's value.
         * @return this builder for chaining.
         */
        public ObjectSchemaBuilder withRequiredProperty(String name, JsonObject schema) {
            this.properties.put(name, schema);
            this.required.add(name);
            return this;
        }

        /**
         * Finalizes and builds the {@link JsonObject} for the object schema.
         *
         * @return the complete object schema as a JsonObject.
         */
        public JsonObject build() {
            JsonObject schema = new JsonObject();
            schema.addProperty("type", "object");

            if (!properties.isEmpty()) {
                JsonObject propertiesObject = new JsonObject();
                for (Map.Entry<String, JsonObject> entry : properties.entrySet()) {
                    propertiesObject.add(entry.getKey(), entry.getValue());
                }
                schema.add("properties", propertiesObject);
            }

            if (!required.isEmpty()) {
                JsonArray requiredArray = new JsonArray();
                for (String req : required) {
                    requiredArray.add(req);
                }
                schema.add("required", requiredArray);
            }

            return schema;
        }
    }
}
