package moe.wolfgirl.probejs.next.plugin.builtins.events;

import com.google.common.collect.ArrayListMultimap;
import com.mojang.datafixers.util.Pair;
import dev.latvian.mods.kubejs.event.EventGroup;
import dev.latvian.mods.kubejs.event.EventGroups;
import dev.latvian.mods.kubejs.event.EventHandler;
import dev.latvian.mods.kubejs.event.KubeEvent;
import dev.latvian.mods.kubejs.script.ScriptType;
import dev.latvian.mods.kubejs.typings.Info;
import moe.wolfgirl.probejs.next.ClassPath;
import moe.wolfgirl.probejs.next.plugin.ProbeJSPlugin;
import moe.wolfgirl.probejs.next.typescript.base.DocumentRegistrar;
import com.google.common.collect.Multimap;
import moe.wolfgirl.probejs.next.typescript.document.ClassDecl;
import moe.wolfgirl.probejs.next.typescript.document.Members;
import moe.wolfgirl.probejs.next.typescript.document.Types;
import moe.wolfgirl.probejs.next.typescript.document.base.KindAware;
import moe.wolfgirl.probejs.next.typescript.document.members.MethodDecl;
import moe.wolfgirl.probejs.next.typescript.transpiler.TypeConverter;


import java.util.*;

public class Events extends ProbeJSPlugin {
    public static final ClassPath STARTUP_EVENTS = ClassPath.sided(ScriptType.STARTUP, "events");
    public static final ClassPath SERVER_EVENTS = ClassPath.sided(ScriptType.SERVER, "events");
    public static final ClassPath CLIENT_EVENTS = ClassPath.sided(ScriptType.CLIENT, "events");

    // Skips events that are intended to be generated by other plugins
    public static final Set<Pair<String, String>> SKIP_EVENTS = new HashSet<>();

    @Override
    public void addSidedDocuments(DocumentRegistrar registrar) {
        Multimap<NamespaceAndSide, EventHandler> allHandlers = ArrayListMultimap.create();
        TypeConverter converter = new TypeConverter();

        for (Map.Entry<String, EventGroup> entry : EventGroups.ALL.get().map().entrySet()) {
            String groupName = entry.getKey();
            EventGroup group = entry.getValue();

            for (EventHandler handler : group.getHandlers().values()) {
                if (SKIP_EVENTS.contains(Pair.of(groupName, handler.name))) continue;
                if (handler.scriptTypePredicate.test(ScriptType.SERVER)) {
                    allHandlers.put(new NamespaceAndSide(groupName, ScriptType.SERVER), handler);
                }
                if (handler.scriptTypePredicate.test(ScriptType.CLIENT)) {
                    allHandlers.put(new NamespaceAndSide(groupName, ScriptType.CLIENT), handler);
                }
                if (handler.scriptTypePredicate.test(ScriptType.STARTUP)) {
                    allHandlers.put(new NamespaceAndSide(groupName, ScriptType.STARTUP), handler);
                }
            }
        }


        for (Map.Entry<NamespaceAndSide, Collection<EventHandler>> entry : allHandlers.asMap().entrySet()) {
            String namespace = entry.getKey().namespace;
            ScriptType scriptType = entry.getKey().scriptType;
            Collection<EventHandler> handlers = entry.getValue();

            ClassPath writeTo = switch (scriptType) {
                case SERVER -> SERVER_EVENTS;
                case CLIENT -> CLIENT_EVENTS;
                case STARTUP -> STARTUP_EVENTS;
            };

            registrar.addGlobal(writeTo.append(namespace), generateEventNamespace(writeTo, namespace, handlers, converter));
        }
    }

    private record NamespaceAndSide(String namespace, ScriptType scriptType) {
    }

    private static ClassDecl generateEventNamespace(ClassPath base, String namespace, Collection<EventHandler> eventHandlers, TypeConverter converter) {
        var classBuilder = Members.clazz(base.append(namespace)).kind(KindAware.Kind.NAMESPACE).noExport();

        for (EventHandler handler : eventHandlers) {
            if (handler.target != null) classBuilder.member(generateMethod(handler, converter, true));
            if (!handler.targetRequired) classBuilder.member(generateMethod(handler, converter, false));
        }

        return classBuilder.build();
    }

    private static MethodDecl generateMethod(EventHandler handler, TypeConverter converter, boolean useExtra) {
        var methodBuilder = Members.method(handler.name);

        if (useExtra) {
            var extraType = converter.convertType(handler.target.describeType);
            Types.markAsInput(extraType);
            methodBuilder.param("extra", extraType);
        }

        Class<?> eventClass = handler.eventType.get();
        methodBuilder.param("handler", Types.lambda(builder -> {
            builder.param("event", Types.clazz(eventClass).asMaybeGeneric());
        }));

        MethodDecl methodDecl = methodBuilder.build();
        for (Info info : eventClass.getAnnotationsByType(Info.class)) {
            methodDecl.addComments(info.value());
        }
        return methodDecl;
    }

    @Override
    public boolean allowClassInDiscovery(Class<?> clazz) {
        return KubeEvent.class.isAssignableFrom(clazz);
    }
}
